const EMAIL=/^[^\s@<>"?&#]+@[^\s@<>"?&#]+\.[^\s@<>"?&#]+$/;
const H={'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Robots-Tag':'noindex, nofollow, noarchive','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; style-src 'self'; img-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'"};
const E=new TextEncoder(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const iso=()=>new Date().toISOString(),plus=n=>new Date(Date.now()+n*60000).toISOString(),norm=v=>String(v||'').trim().toLowerCase();
function b64(b){let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function random(n=32){const b=new Uint8Array(n);crypto.getRandomValues(b);return b64(b)}
function otp(){const a=new Uint32Array(1);do crypto.getRandomValues(a);while(a[0]>=4294000000);return String(a[0]%1000000).padStart(6,'0')}
async function hash(v){const d=await crypto.subtle.digest('SHA-256',E.encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function mac(k,v){const key=await crypto.subtle.importKey('raw',E.encode(k),{name:'HMAC',hash:'SHA-256'},false,['sign']);const d=await crypto.subtle.sign('HMAC',key,E.encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function ck(r,n){for(const p of(r.headers.get('Cookie')||'').split(';')){const i=p.indexOf('=');if(i>0&&p.slice(0,i).trim()===n)return p.slice(i+1).trim()}return''}
function page(c,s=200,x={}){return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>My Recovery Tags | PeterHamRN.com</title><link rel="icon" href="/peterhamrn-logo.svg"><link rel="stylesheet" href="/assets/recovery.css?v=20260925d"></head><body><header><a class="brand" href="/"><img src="/peterhamrn-logo.svg" width="38" height="44" alt="">PeterHamRN<span>.com</span></a></header><main><article class="card activation-card"><div class="identity"><img src="/peterhamrn-logo.svg" width="104" height="104" alt="PH shield logo"><p class="eyebrow">Lost item recovery</p></div>${c}</article></main><footer><a class="footer-cta" href="/recovery-tags">Find this handy? Need more tags? Get another Recovery Tag →</a><div>Peter Ham Solutions · <a href="/">PeterHamRN.com</a></div></footer></body></html>`,{status:s,headers:{...H,...x}})}
const err=(t,p,s=400)=>page(`<div class="content"><h1>${esc(t)}</h1><p>${esc(p)}</p></div>`,s);
function emailForm(m=''){return page(`<div class="content"><h1>My Recovery Tags</h1><p class="activation-copy">Enter the email address you used to activate your tags. We’ll send a six-digit sign-in code.</p>${m?`<p class="form-error">${esc(m)}</p>`:''}<form method="post" class="recovery-form"><input type="hidden" name="action" value="send"><label class="field">Email address<input name="email" type="email" autocomplete="email" required></label><button class="action" type="submit">SEND SIGN-IN CODE</button></form></div>`)}
function codeForm(email,id,m=''){return page(`<div class="content"><h1>Check Your Email</h1><p>Enter the six-digit code sent to <strong>${esc(email)}</strong>.</p>${m?`<p class="form-error">${esc(m)}</p>`:''}<form method="post" class="recovery-form"><input type="hidden" name="action" value="verify"><input type="hidden" name="challenge_id" value="${esc(id)}"><input type="hidden" name="email" value="${esc(email)}"><label class="field">Verification code<input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required></label><button class="action" type="submit">SIGN IN</button></form></div>`)}
async function send(request,env,email){email=norm(email);if(!EMAIL.test(email))return emailForm('Enter a valid email address.');if(!env.RESEND_API_KEY||!env.RECOVERY_OTP_SECRET)return err('Temporarily unavailable','Sign-in is not configured.',503);
 const exists=await env.RECOVERY_DB.prepare("SELECT 1 ok FROM owners o JOIN recovery_tags t ON t.owner_id=o.id WHERE lower(o.email)=? AND t.status='active' LIMIT 1").bind(email).first();
 if(!exists)return emailForm('No active Recovery Tags were found for that email address.');
 const ip=await mac(env.RECOVERY_OTP_SECRET,'owner-ip:'+(request.headers.get('CF-Connecting-IP')||'unknown')),since=new Date(Date.now()-3600000).toISOString();
 const last=await env.RECOVERY_DB.prepare('SELECT created_at FROM recovery_owner_challenges WHERE email=? ORDER BY created_at DESC LIMIT 1').bind(email).first();if(last&&Date.now()-Date.parse(last.created_at)<60000)return emailForm('Please wait one minute before requesting another code.');
 const count=await env.RECOVERY_DB.prepare('SELECT COUNT(*) n FROM recovery_owner_challenges WHERE created_at>=? AND (email=? OR ip_mac=?)').bind(since,email,ip).first();if(Number(count?.n||0)>=5)return emailForm('Too many sign-in requests. Please try again later.');
 const id=crypto.randomUUID(),code=otp(),cm=await mac(env.RECOVERY_OTP_SECRET,`owner:${id}:${email}:${code}`);await env.RECOVERY_DB.prepare('INSERT INTO recovery_owner_challenges(id,email,code_mac,ip_mac,expires_at) VALUES(?,?,?,?,?)').bind(id,email,cm,ip,plus(10)).run();
 const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':id},body:JSON.stringify({from:'Recovery Tags <recovery@peterhamrn.com>',to:[email],reply_to:'recovery@peterhamrn.com',subject:'Your Recovery Tags sign-in code',text:`Your Recovery Tags sign-in code is ${code}. It expires in 10 minutes. If you did not request this code, you can ignore this email.`})});if(!r.ok){await env.RECOVERY_DB.prepare('DELETE FROM recovery_owner_challenges WHERE id=?').bind(id).run();return err('Email could not be sent','Please try again in a few minutes.',503)}return codeForm(email,id)}
async function session(request,env){const raw=ck(request,'recovery_owner_session');if(!raw)return null;const sh=await hash(raw);return env.RECOVERY_DB.prepare('SELECT email FROM recovery_owner_sessions WHERE session_hash=? AND expires_at>? LIMIT 1').bind(sh,iso()).first()}
async function dashboard(env,email){const q=await env.RECOVERY_DB.prepare("SELECT t.public_token,t.item_label,t.status,o.display_name,o.phone,o.show_name,o.allow_call,o.allow_text,o.allow_email FROM recovery_tags t JOIN owners o ON o.id=t.owner_id WHERE lower(o.email)=? AND t.status='active' ORDER BY t.created_at DESC").bind(email).all();const cards=(q.results||[]).map(t=>`<details class="tag-manage"><summary><span><strong>${esc(t.item_label)}</strong><small>Active Recovery Tag</small></span><b aria-hidden="true">›</b></summary><form method="post" class="recovery-form compact"><input type="hidden" name="action" value="save"><input type="hidden" name="token" value="${esc(t.public_token)}"><label class="field">Item name<input name="item_label" value="${esc(t.item_label)}" required maxlength="100"></label><label class="field">Your name<input name="display_name" value="${esc(t.display_name)}" required maxlength="100"></label><label class="field">Phone number (optional)<input name="phone" type="tel" value="${esc(t.phone||'')}" maxlength="30"></label><fieldset><legend>Finder options</legend><div class="preference-grid"><label class="check"><input type="checkbox" name="show_name" value="1" ${t.show_name?'checked':''}> Show my first name</label><label class="check"><input type="checkbox" name="allow_email" value="1" ${t.allow_email?'checked':''}> Email me</label><label class="check"><input type="checkbox" name="allow_text" value="1" ${t.allow_text?'checked':''}> Text me</label><label class="check"><input type="checkbox" name="allow_call" value="1" ${t.allow_call?'checked':''}> Call me</label></div></fieldset><button class="action" type="submit">SAVE CHANGES</button><a class="manage-link" href="/find/${esc(t.public_token)}">View recovery page →</a></form></details>`).join('');return page(`<div class="content"><h1>My Recovery Tags</h1><p class="verified">✓ Signed in as ${esc(email)}</p><div class="tag-list">${cards||'<p>No active tags found.</p>'}</div><form method="post" class="secondary-form"><input type="hidden" name="action" value="signout"><button class="secondary-action" type="submit">SIGN OUT</button></form></div>`)}
function normPhone(v){const raw=String(v||'').trim(),d=raw.replace(/\D/g,'');if(!d)return'';if(d.length===10)return'+1'+d;if(d.length===11&&d[0]==='1')return'+'+d;if(raw.startsWith('+')&&d.length>=7&&d.length<=15)return'+'+d;return''}
export async function onRequest({request,env}){if(request.method!=='GET'&&request.method!=='POST')return err('Method not allowed','',405);let s;try{s=await session(request,env)}catch{return err('Temporarily unavailable','Please try again shortly.',503)}if(request.method==='GET')return s?dashboard(env,s.email):emailForm();
 const origin=request.headers.get('Origin');if(origin&&origin!=='null'){let host='';try{host=new URL(origin).hostname.toLowerCase()}catch{}if(host!=='peterhamrn.com'&&!host.endsWith('.peterhamrn.com'))return err('Request blocked','Please reopen My Recovery Tags and retry.',403)}let f;try{f=await request.formData()}catch{return err('Bad request','Please try again.',400)}const a=f.get('action');
 if(a==='send')return send(request,env,f.get('email'));if(a==='verify'){const id=String(f.get('challenge_id')||''),email=norm(f.get('email')),code=String(f.get('code')||'').trim(),c=await env.RECOVERY_DB.prepare('SELECT * FROM recovery_owner_challenges WHERE id=? AND email=? LIMIT 1').bind(id,email).first();if(!c||c.consumed_at||Date.parse(c.expires_at)<=Date.now()||c.attempts>=5)return codeForm(email,id,'That code is invalid or expired.');const expected=await mac(env.RECOVERY_OTP_SECRET,`owner:${id}:${email}:${code}`);if(!/^[0-9]{6}$/.test(code)||expected!==c.code_mac){await env.RECOVERY_DB.prepare('UPDATE recovery_owner_challenges SET attempts=attempts+1 WHERE id=?').bind(id).run();return codeForm(email,id,'That sign-in code is not correct.')}const raw=random(),sh=await hash(raw);await env.RECOVERY_DB.batch([env.RECOVERY_DB.prepare('INSERT INTO recovery_owner_sessions(session_hash,email,expires_at) VALUES(?,?,?)').bind(sh,email,plus(1440)),env.RECOVERY_DB.prepare('UPDATE recovery_owner_challenges SET consumed_at=? WHERE id=?').bind(iso(),id)]);const r=await dashboard(env,email);r.headers.set('Set-Cookie',`recovery_owner_session=${raw}; Path=/tags; Max-Age=86400; HttpOnly; Secure; SameSite=Strict`);return r}
 if(a==='signout'){const raw=ck(request,'recovery_owner_session');if(raw)await env.RECOVERY_DB.prepare('DELETE FROM recovery_owner_sessions WHERE session_hash=?').bind(await hash(raw)).run();const r=emailForm();r.headers.set('Set-Cookie','recovery_owner_session=; Path=/tags; Max-Age=0; HttpOnly; Secure; SameSite=Strict');return r}
 if(a==='save'&&s){const token=String(f.get('token')||''),name=String(f.get('display_name')||'').trim(),item=String(f.get('item_label')||'').trim(),phone=normPhone(f.get('phone')),show=f.get('show_name')==='1'?1:0,ae=f.get('allow_email')==='1'?1:0,at=f.get('allow_text')==='1'?1:0,ac=f.get('allow_call')==='1'?1:0;if(!name||!item)return err('Missing information','Name and item name are required.');if((at||ac)&&!phone)return err('Phone number required','Enter a valid phone number to enable calls or texts.');if(!ae&&!at&&!ac)return err('Contact method required','Choose at least one way for a finder to contact you.');const row=await env.RECOVERY_DB.prepare("SELECT t.id tag_id,o.id owner_id FROM recovery_tags t JOIN owners o ON o.id=t.owner_id WHERE t.public_token=? AND t.status='active' AND lower(o.email)=? LIMIT 1").bind(token,s.email).first();if(!row)return err('Tag unavailable','That tag is not available in this account.',404);await env.RECOVERY_DB.batch([env.RECOVERY_DB.prepare('UPDATE owners SET display_name=?,phone=?,show_name=?,allow_call=?,allow_text=?,allow_email=?,updated_at=? WHERE id=?').bind(name,phone||null,show,ac,at,ae,iso(),row.owner_id),env.RECOVERY_DB.prepare('UPDATE recovery_tags SET item_label=?,updated_at=? WHERE id=?').bind(item,iso(),row.tag_id)]);return dashboard(env,s.email)}return err('Bad request','Please try again.',400)}
